name: build webpage

on:
  push:
    branches:
    - documentation_new

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      
    - run: mkdir build

    - name: Generate index page
      uses: docker://slatedocs/slate:v2.12.0
      with:
        entrypoint: ls
        args: .
        working-directory: /tmp
      working-directory: /
 

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: dist




